-- Athenaeum V1 - Supabase setup
create table if not exists public.athenaeum_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_key text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id, profile_key)
);

create table if not exists public.athenaeum_telegram_pairing (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile_key text not null,
  pair_code text not null unique,
  timezone text not null default 'Europe/Brussels',
  morning_time time not null default '08:00',
  reminder_time time not null default '18:00',
  telegram_chat_id text,
  enabled boolean not null default false,
  expires_at timestamptz,
  last_morning_sent date,
  last_reminder_sent date,
  updated_at timestamptz not null default now()
);

alter table public.athenaeum_state enable row level security;
alter table public.athenaeum_telegram_pairing enable row level security;

drop policy if exists "state select own" on public.athenaeum_state;
drop policy if exists "state insert own" on public.athenaeum_state;
drop policy if exists "state update own" on public.athenaeum_state;
create policy "state select own" on public.athenaeum_state for select using (auth.uid()=user_id);
create policy "state insert own" on public.athenaeum_state for insert with check (auth.uid()=user_id);
create policy "state update own" on public.athenaeum_state for update using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "telegram select own" on public.athenaeum_telegram_pairing;
drop policy if exists "telegram insert own" on public.athenaeum_telegram_pairing;
drop policy if exists "telegram update own" on public.athenaeum_telegram_pairing;
create policy "telegram select own" on public.athenaeum_telegram_pairing for select using (auth.uid()=user_id);
create policy "telegram insert own" on public.athenaeum_telegram_pairing for insert with check (auth.uid()=user_id);
create policy "telegram update own" on public.athenaeum_telegram_pairing for update using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- After deploying the telegram-bot Edge Function, schedule it every 15 minutes.
-- Store your project URL and publishable key in Vault first; see docs/TELEGRAM_SETUP.txt.
-- Example:
-- select cron.schedule('athenaeum-telegram-reminders','*/15 * * * *', $$
--   select net.http_post(
--     url := (select decrypted_secret from vault.decrypted_secrets where name='project_url') || '/functions/v1/telegram-bot',
--     headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='publishable_key')),
--     body := jsonb_build_object('mode','schedule')
--   );
-- $$);
