import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const TELEGRAM_BOT_TOKEN = Deno.env.get('TELEGRAM_BOT_TOKEN') || ''
const TELEGRAM_WEBHOOK_SECRET = Deno.env.get('TELEGRAM_WEBHOOK_SECRET') || ''
const SCHEDULER_SECRET = Deno.env.get('SCHEDULER_SECRET') || ''
const APP_URL = Deno.env.get('ATHENAEUM_APP_URL') || 'https://loic1311.github.io/Athenaeum/'
const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

async function telegram(method:string, body:any={}){
  if(!TELEGRAM_BOT_TOKEN) throw new Error('TELEGRAM_BOT_TOKEN ontbreekt in Supabase Secrets.');
  const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})
  const data=await r.json().catch(()=>({}))
  if(!r.ok||data?.ok===false) throw new Error(data?.description||JSON.stringify(data))
  return data?.result??data
}
function cors(){return {'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type, x-telegram-bot-api-secret-token'}}
function localParts(timeZone:string){const p=new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const m=Object.fromEntries(p.map(x=>[x.type,x.value]));const date=`${m.year}-${m.month}-${m.day}`;const dow=new Date(date+'T12:00:00Z').getUTCDay();return{date,time:`${m.hour}:${m.minute}`,dow}}
function within15(now:string,target:string){const [h,m]=now.split(':').map(Number),[th,tm]=String(target).slice(0,5).split(':').map(Number);const a=h*60+m,b=th*60+tm;return a>=b&&a<b+15}
function daysUntilDow(dow:number,target:number){return (Number(target)-Number(dow)+7)%7}
function daysUntilMonthDay(localDate:string,targetDay:number){const now=new Date(localDate+'T12:00:00Z'),day=Math.max(1,Math.min(28,Number(targetDay)||28));let target=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),day,12));if(target<now)target=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,day,12));return Math.round((target.getTime()-now.getTime())/86400000)}
function hasExamPaths(pa:any){return Object.values(pa?.learning_paths||{}).some((v:any)=>v?.active&&v?.exam)}
function examText(pa:any,lp:any,alertsOnly=false){if(!hasExamPaths(pa))return 'Geen examens ingepland.';const ec=pa?.exam_config||{},pc={weekly_notice_days:2,monthly_notice_days:3,...(pa?.plan_config||{})},w={enabled:true,day:0,...(ec.weekly||{})},m={enabled:true,day_of_month:28,...(ec.monthly||{})},lines:string[]=[];if(w.enabled){const d=daysUntilDow(lp.dow,w.day);if(!alertsOnly||d<=Math.max(0,Number(pc.weekly_notice_days||2)))lines.push(d===0?'Weekexamen: vandaag.':d===1?'Weekexamen: morgen.':`Weekexamen: over ${d} dagen (${['zondag','maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag'][Number(w.day)]||'gepland'}).`)}if(m.enabled){const d=daysUntilMonthDay(lp.date,m.day_of_month);if(!alertsOnly||d<=Math.max(0,Number(pc.monthly_notice_days||3)))lines.push(d===0?'Mastery check: vandaag.':d===1?'Mastery check: morgen.':`Mastery check: over ${d} dagen (dag ${m.day_of_month} van de maand).`)}return lines.length?lines.join('\n'):(alertsOnly?'':'Geen examens ingepland.')}
function hasRelevantExamAlert(pa:any,lp:any){return !!examText(pa,lp,true)}
async function authUser(req:Request){const auth=req.headers.get('authorization')||'';const token=auth.replace(/^Bearer\s+/i,'');if(!token)throw new Error('Aanmelding ontbreekt.');const {data,error}=await supabase.auth.getUser(token);if(error||!data.user)throw new Error('Ongeldige gebruikerssessie.');return data.user}
async function botUsername(){const me=await telegram('getMe');return me?.username||''}
async function ensureWebhook(){if(!TELEGRAM_BOT_TOKEN||!TELEGRAM_WEBHOOK_SECRET)return {ok:false,reason:'secrets_missing'};const expected=`${SUPABASE_URL}/functions/v1/telegram-bot`;const info=await telegram('getWebhookInfo');if(info?.url!==expected){await telegram('setWebhook',{url:expected,secret_token:TELEGRAM_WEBHOOK_SECRET,drop_pending_updates:false});return {ok:true,changed:true,url:expected}}return {ok:true,changed:false,url:expected}}
async function handleTelegramUpdate(req:Request,update:any){if(TELEGRAM_WEBHOOK_SECRET&&req.headers.get('x-telegram-bot-api-secret-token')!==TELEGRAM_WEBHOOK_SECRET)throw new Error('Ongeldig Telegram webhook-secret.');const msg=update?.message;if(!msg?.chat?.id||!msg?.text)return;const match=String(msg.text).trim().match(/^\/start\s+([A-Z0-9]{4,12})$/i);if(!match){await telegram('sendMessage',{chat_id:msg.chat.id,text:'🏛️ Athenaeum Bot\nKoppel via Paideia → Instellingen → Telegram en stuur daarna /start CODE.'});return}const code=match[1].toUpperCase();const {data,error}=await supabase.from('athenaeum_telegram_pairing').select('*').eq('pair_code',code).gt('expires_at',new Date().toISOString()).maybeSingle();if(error||!data){await telegram('sendMessage',{chat_id:msg.chat.id,text:'Deze koppelcode is ongeldig of verlopen.'});return}await supabase.from('athenaeum_telegram_pairing').update({telegram_chat_id:String(msg.chat.id),enabled:true,updated_at:new Date().toISOString()}).eq('id',data.id);await telegram('sendMessage',{chat_id:msg.chat.id,text:'✅ Athenaeum is gekoppeld. Ik stuur voortaan alleen jouw Paideia-planning, relevante examenaftelling en reminder volgens jouw profielinstellingen.',reply_markup:{inline_keyboard:[[{text:'Open Athenaeum',url:APP_URL}]]}})}
async function pairRow(userId:string,profileKey:string='main'){const {data,error}=await supabase.from('athenaeum_telegram_pairing').select('*').eq('user_id',userId).eq('profile_key',profileKey||'main').maybeSingle();if(error)throw error;return data}
function paideiaFromPayload(payload:any){return payload?.data?.paideia_state||payload?.paideia_state||{}}
async function stateFor(row:any){const {data}=await supabase.from('athenaeum_state').select('payload').eq('user_id',row.user_id).eq('profile_key',row.profile_key||'main').maybeSingle();return paideiaFromPayload(data?.payload||{})}
function pathScheduled(v:any,dow:number){const ds=Array.isArray(v?.study_days)?v.study_days.map(Number):[0,1,2,3,4,5,6];return ds.includes(Number(dow))}
function scheduledTelegramEntries(pa:any,dow:number){const labels:any={ancient:['🏺','Oude Geschiedenis'],early_modern:['🕯️','Vroegmoderne Tijd'],general_history:['🌍','Algemene Geschiedenis'],general_knowledge:['🧠','Algemene Kennis'],pharmacy:['⚗️','Farmacie'],skill:['🛠️','Algemene Vaardigheden']};const defaults:any={ancient:{active:false,telegram:true,minutes:20,priority:'high',study_days:[1,2,3,4,5]},early_modern:{active:false,telegram:true,minutes:20,priority:'high',study_days:[1,2,3,4,5]},general_history:{active:true,telegram:true,minutes:10,priority:'normal',study_days:[1,2,3,4,5]},general_knowledge:{active:true,telegram:true,minutes:10,priority:'light',study_days:[1,2,3,4,5]},pharmacy:{active:false,telegram:true,minutes:20,priority:'normal',study_days:[1,2,3,4,5]},skill:{active:false,telegram:true,minutes:12,priority:'light',study_days:[6,0]}};const paths={...defaults,...(pa.learning_paths||{})};const scheduled=Object.entries(paths).filter(([k,v]:any)=>v?.active&&v?.telegram!==false&&labels[k]&&pathScheduled(v,dow));if(!scheduled.length)return[];const rank:any={high:0,normal:1,light:2};scheduled.sort((a:any,b:any)=>(rank[(a[1] as any).priority]??1)-(rank[(b[1] as any).priority]??1));const core=scheduled.filter(([,v]:any)=>['high','normal'].includes(v?.priority)),light=scheduled.filter(([,v]:any)=>v?.priority==='light'),pc={max_daily_minutes:60,light_every:3,...(pa?.plan_config||{})},every=Math.max(1,Math.min(14,Number(pc.light_every||3))),candidates=[...core];if(light.length&&Number(pa.daily_count||0)%every===0)candidates.push(light[Math.floor(Number(pa.daily_count||0)/every)%light.length]);const pool=candidates.length?candidates:scheduled,cap=Math.max(10,Math.min(240,Number(pc.max_daily_minutes||60))),out:any[]=[];let total=0;for(const entry of pool){const mins=Math.max(5,Math.min(90,Number((entry[1] as any)?.minutes||10)));if(!out.length||total+mins<=cap){out.push(entry);total+=mins}}return out.length?out:scheduled.slice(0,1)}
function scheduledTelegramLines(pa:any,dow:number){const labels:any={ancient:['🏺','Oude Geschiedenis'],early_modern:['🕯️','Vroegmoderne Tijd'],general_history:['🌍','Algemene Geschiedenis'],general_knowledge:['🧠','Algemene Kennis'],pharmacy:['⚗️','Farmacie'],skill:['🛠️','Algemene Vaardigheden']};return scheduledTelegramEntries(pa,dow).map(([k,v]:any)=>`${labels[k][0]} ${v.minutes||10} min ${labels[k][1]}`)}
function hasScheduledStudy(pa:any,dow:number){return scheduledTelegramEntries(pa,dow).length>0}
function hasMorningContent(pa:any,lp:any){return hasScheduledStudy(pa,lp.dow)||hasRelevantExamAlert(pa,lp)}
function morningMessage(pa:any,lp:any){const streak=pa.streak||0,cubes=pa.icecubes??2,count=(pa.daily_count||0)+1,lines=scheduledTelegramLines(pa,lp.dow),alert=examText(pa,lp,true);return `🏛️ Athenaeum — dag ${count}\n🔥 Streak: ${streak} · 🧊 ${cubes}\n\nVandaag in Paideia:\n${lines.length?lines.join('\n'):'Geen automatisch leerpad gepland.'}${alert?`\n\n📅 ${alert}`:''}`}
async function sendTest(userId:string,profileKey:string='main'){const row=await pairRow(userId,profileKey);if(!row?.enabled||!row.telegram_chat_id)throw new Error('Telegram is nog niet gekoppeld.');const pa=await stateFor(row),lp=localParts(row.timezone||'Europe/Brussels');await telegram('sendMessage',{chat_id:row.telegram_chat_id,text:'🧪 Testmelding\n\n'+morningMessage(pa,lp),reply_markup:{inline_keyboard:[[{text:'Start Paideia',url:`${APP_URL}?open=paideia`}]]}});return true}
async function schedule(){const {data:rows,error}=await supabase.from('athenaeum_telegram_pairing').select('*').eq('enabled',true).not('telegram_chat_id','is',null);if(error)throw error;for(const r of rows||[]){const lp=localParts(r.timezone||'Europe/Brussels'),pa=await stateFor(r),completed=pa.last_completed===lp.date;if(hasMorningContent(pa,lp)&&within15(lp.time,String(r.morning_time))&&r.last_morning_sent!==lp.date){await telegram('sendMessage',{chat_id:r.telegram_chat_id,text:morningMessage(pa,lp),reply_markup:{inline_keyboard:[[{text:'Start Paideia',url:`${APP_URL}?open=paideia`}]]}});await supabase.from('athenaeum_telegram_pairing').update({last_morning_sent:lp.date}).eq('id',r.id)}if(hasScheduledStudy(pa,lp.dow)&&!completed&&within15(lp.time,String(r.reminder_time))&&r.last_reminder_sent!==lp.date){await telegram('sendMessage',{chat_id:r.telegram_chat_id,text:`⏳ Je Paideia-dagsessie staat nog open.\n🔥 Huidige streak: ${pa.streak||0}\n🧊 IJsblokjes: ${pa.icecubes??2}\n${examText(pa,lp)}\n\nOpen Paideia om je resterende gepersonaliseerde leerpaden af te ronden.`,reply_markup:{inline_keyboard:[[{text:'Ga naar Paideia',url:`${APP_URL}?open=paideia`}]]}});await supabase.from('athenaeum_telegram_pairing').update({last_reminder_sent:lp.date}).eq('id',r.id)}}}
Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:cors()});
  try{
    const body=await req.json().catch(()=>({}));
    if(body?.update_id){await handleTelegramUpdate(req,body);return new Response(JSON.stringify({ok:true}),{headers:cors()})}
    if(body?.mode==='schedule'){if(SCHEDULER_SECRET&&body?.secret!==SCHEDULER_SECRET)throw new Error('Ongeldig scheduler-secret.');await schedule();return new Response(JSON.stringify({ok:true}),{headers:cors()})}
    if(body?.mode==='setup_webhook'){
      if(!SCHEDULER_SECRET||body?.secret!==SCHEDULER_SECRET)throw new Error('Ongeldig setup-secret.');
      if(!TELEGRAM_WEBHOOK_SECRET)throw new Error('TELEGRAM_WEBHOOK_SECRET ontbreekt.');
      const result=await telegram('setWebhook',{url:`${SUPABASE_URL}/functions/v1/telegram-bot`,secret_token:TELEGRAM_WEBHOOK_SECRET,drop_pending_updates:false});
      return new Response(JSON.stringify({ok:true,result}),{headers:cors()});
    }
    const user=await authUser(req);
    if(body?.mode==='health'){
      const username=await botUsername();const webhook=await ensureWebhook();
      return new Response(JSON.stringify({ok:true,bot_username:username,app_url:APP_URL,webhook}),{headers:cors()});
    }
    if(body?.mode==='test'){await sendTest(user.id,body?.profile_key||'main');return new Response(JSON.stringify({ok:true}),{headers:cors()})}
    if(body?.mode==='status'){const row=await pairRow(user.id,body?.profile_key||'main'),username=await botUsername();return new Response(JSON.stringify({ok:true,connected:!!(row?.enabled&&row?.telegram_chat_id),bot_username:username}),{headers:cors()})}
    return new Response(JSON.stringify({ok:true}),{headers:cors()});
  }catch(e){return new Response(JSON.stringify({ok:false,error:String(e?.message||e)}),{status:400,headers:cors()})}
})
