(function(){
'use strict';
const S=()=>window.AthStore;
const CLOUD_KEY='main';
let timer=null,dirtyTimer=null,focusBound=false,visibilityBound=false,onlineBound=false,activePid='';
const running=new Map();
let suspendDirty=false;
function cfg(pid){return S().getProfileData(pid,'sync',{url:'',key:'',email:'',access_token:'',refresh_token:'',expires_at:0,user:null,enabled:false,last_sync:0,last_error:'',last_direction:'',cloud_profile_key:CLOUD_KEY,dirty_at:0})}
function saveCfg(pid,c){suspendDirty=true;S().setProfileData(pid,'sync',{...c,cloud_profile_key:CLOUD_KEY});suspendDirty=false}
function status(pid){const c=cfg(pid);return{enabled:!!c.enabled,signed_in:!!c.user?.id,email:c.user?.email||c.email||'',last_sync:c.last_sync||0,last_error:c.last_error||'',last_direction:c.last_direction||'',cloud_key:CLOUD_KEY,syncing:running.has(pid)}}
function baseHeaders(key,extra={}){return{'apikey':key,'Content-Type':'application/json',...extra}}
async function rawRequest(url,key,path,opt={}){if(!url||!key)throw new Error('Supabase URL/key ontbreken.');const r=await fetch(url.replace(/\/$/,'')+path,{...opt,headers:baseHeaders(key,opt.headers||{})});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.error||`${r.status} ${r.statusText}`);return data}
async function request(pid,path,opt={}){const c=cfg(pid);return rawRequest(c.url,c.key,path,opt)}
async function storeSession(pid,d){const c=cfg(pid);saveCfg(pid,{...c,access_token:d.access_token||c.access_token,refresh_token:d.refresh_token||c.refresh_token,user:d.user||c.user,expires_at:Date.now()+((d.expires_in||3600)*1000),enabled:true,last_error:''})}
async function auth(pid,email,password,signup=false){const c=cfg(pid);saveCfg(pid,{...c,email});const d=await request(pid,signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});if(d.access_token)await storeSession(pid,d);return d}
async function access(pid){let c=cfg(pid);if(c.access_token&&c.expires_at>Date.now()+60000)return c.access_token;if(!c.refresh_token)throw new Error('Meld eerst aan.');const d=await request(pid,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:c.refresh_token})});await storeSession(pid,d);return d.access_token}
function itemKey(x){if(x==null)return null;if(typeof x!=='object')return `p:${String(x)}`;for(const k of ['id','attempt_id','pack_id','work_id','key','date','source_id','doi','title'])if(x[k]!=null)return `${k}:${String(x[k])}`;return null}
function stamp(x){return Number(x?.updated_at||x?.graded_at||x?.analysis_updated_at||x?.created_at||0)||0}
function mergeArrays(a=[],b=[]){if(!Array.isArray(a))a=[];if(!Array.isArray(b))b=[];if([...a,...b].every(x=>x==null||typeof x!=='object'))return [...new Set([...a,...b])];const map=new Map(),loose=[];for(const x of [...a,...b]){const k=itemKey(x);if(!k){loose.push(x);continue}const old=map.get(k);if(!old||stamp(x)>=stamp(old))map.set(k,old&&typeof old==='object'&&typeof x==='object'?mergeValue(old,x):x)}return[...map.values(),...loose]}
function plain(x){return x&&typeof x==='object'&&!Array.isArray(x)}
function mergeValue(a,b){if(a==null)return b;if(b==null)return a;if(Array.isArray(a)||Array.isArray(b))return mergeArrays(Array.isArray(a)?a:[],Array.isArray(b)?b:[]);if(plain(a)&&plain(b)){if(stamp(a)&&stamp(b)&&Math.abs(stamp(a)-stamp(b))>0){const newer=stamp(b)>stamp(a)?b:a,older=newer===b?a:b;const out={...older,...newer};for(const k of ['history','weekly_scores','monthly_scores','completed_dates','attempts','recent_signatures'])if(Array.isArray(a[k])||Array.isArray(b[k]))out[k]=mergeArrays(a[k]||[],b[k]||[]);return out}const out={...a};for(const[k,v]of Object.entries(b))out[k]=k in out?mergeValue(out[k],v):v;return out}return b}
function mergePaideia(a={},b={}){const newer=(stamp(b)>=stamp(a))?b:a,older=newer===b?a:b;const out={...older,...newer};for(const k of ['completed_dates','weekly_scores','monthly_scores','history'])out[k]=mergeArrays(a[k]||[],b[k]||[]);out.daily_count=Math.max(Number(a.daily_count||0),Number(b.daily_count||0));out.updated_at=Math.max(stamp(a),stamp(b),Date.now());return out}
function mergeData(a={},b={}){const out={...a};for(const[k,v]of Object.entries(b||{})){if(k==='paideia_state')out[k]=mergePaideia(out[k]||{},v||{});else out[k]=k in out?mergeValue(out[k],v):v}return out}
function profileSnapshot(p){return{id:p.id,name:p.name,avatar:p.avatar,apps:S().profileApps(p),icecubes:p.icecubes,pin_hash:p.pin_hash||'',pin_salt:p.pin_salt||'',updated_at:p.updated_at||0}}
function localData(pid){const data={};Object.keys(localStorage).filter(k=>k.startsWith(`ath_${pid}_`)&&!k.endsWith('_sync')).forEach(k=>{try{data[k.slice(`ath_${pid}_`.length)]=JSON.parse(localStorage.getItem(k))}catch{}});return data}
function openIDB(name){return new Promise((res,rej)=>{const r=indexedDB.open(name,3);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('works'))d.createObjectStore('works',{keyPath:'id'});if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function all(db,store){return new Promise((res,rej)=>{if(!db.objectStoreNames.contains(store))return res([]);const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function put(db,store,val){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(val);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function collectScriptorium(pid){try{const db=await openIDB(`ScriptoriumDB_${pid}`);const works=await all(db,'works'),settings=(await all(db,'settings')).filter(x=>!['v6_sb_config','v6_sync_meta'].includes(x.key));db.close();return{works,settings,updated_at:Date.now()}}catch(e){console.warn('Scriptorium sync collect skipped',e);return{works:[],settings:[],updated_at:0}}}
async function applyScriptorium(pid,remote={}){if(!remote||(!remote.works?.length&&!remote.settings?.length))return;const db=await openIDB(`ScriptoriumDB_${pid}`);const localWorks=await all(db,'works'),localSettings=await all(db,'settings');const wmap=new Map(localWorks.map(x=>[x.id,x]));for(const w of remote.works||[]){const old=wmap.get(w.id);await put(db,'works',old?mergeValue(old,w):w)}const smap=new Map(localSettings.map(x=>[x.key,x]));for(const s of remote.settings||[]){if(['v6_sb_config','v6_sync_meta'].includes(s.key))continue;const old=smap.get(s.key);await put(db,'settings',old?{...old,...s,value:mergeValue(old.value,s.value)}:s)}db.close()}
async function collect(pid){const p=S().loadProfiles().find(x=>x.id===pid);if(!p)throw new Error('Profiel bestaat lokaal niet.');return{schema:2,profile:profileSnapshot(p),data:localData(pid),scriptorium:await collectScriptorium(pid),updated_at:Date.now()}}
function mergeScriptorium(a={},b={}){return{works:mergeArrays(a.works||[],b.works||[]),settings:mergeArrays(a.settings||[],b.settings||[]),updated_at:Math.max(a.updated_at||0,b.updated_at||0,Date.now())}}
function merge(local,remote){if(!remote)return local;const lp=local.profile||{},rp=remote.profile||{},newer=(rp.updated_at||0)>(lp.updated_at||0)?rp:lp;return{schema:2,profile:{...lp,...rp,...newer,id:lp.id},data:mergeData(local.data||{},remote.data||{}),scriptorium:mergeScriptorium(local.scriptorium||{},remote.scriptorium||{}),updated_at:Date.now()}}
async function apply(pid,payload){suspendDirty=true;try{if(payload.profile){const ps=S().loadProfiles(),i=ps.findIndex(p=>p.id===pid);if(i>=0){ps[i]={...ps[i],name:payload.profile.name||ps[i].name,avatar:payload.profile.avatar||ps[i].avatar,apps:Array.isArray(payload.profile.apps)?payload.profile.apps:ps[i].apps,icecubes:payload.profile.icecubes??ps[i].icecubes,pin_hash:payload.profile.pin_hash??ps[i].pin_hash,pin_salt:payload.profile.pin_salt||ps[i].pin_salt,updated_at:Math.max(ps[i].updated_at||0,payload.profile.updated_at||0)};S().saveProfiles(ps)}}for(const[k,v]of Object.entries(payload.data||{}))S().setProfileData(pid,k,v);await applyScriptorium(pid,payload.scriptorium||{})}finally{suspendDirty=false}}
async function queryState(pid,token,userId){let rows=await request(pid,`/rest/v1/athenaeum_state?user_id=eq.${encodeURIComponent(userId)}&profile_key=eq.${CLOUD_KEY}&select=profile_key,payload,updated_at`,{headers:{Authorization:`Bearer ${token}`}});if(Array.isArray(rows)&&rows[0])return rows[0];rows=await request(pid,`/rest/v1/athenaeum_state?user_id=eq.${encodeURIComponent(userId)}&select=profile_key,payload,updated_at&order=updated_at.desc&limit=1`,{headers:{Authorization:`Bearer ${token}`}});return Array.isArray(rows)?rows[0]||null:null}
async function pull(pid){const token=await access(pid),c=cfg(pid),u=c.user;if(!u?.id)throw new Error('Gebruiker ontbreekt.');const row=await queryState(pid,token,u.id);return row?.payload||null}
async function push(pid,payload){const token=await access(pid),c=cfg(pid),u=c.user;if(!u?.id)throw new Error('Gebruikers-ID ontbreekt.');await request(pid,'/rest/v1/athenaeum_state?on_conflict=user_id,profile_key',{method:'POST',headers:{Authorization:`Bearer ${token}`,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:u.id,profile_key:CLOUD_KEY,payload,updated_at:new Date().toISOString()})})}
function emitSync(pid,phase,error=''){try{window.dispatchEvent(new CustomEvent('athenaeum-sync',{detail:{pid,phase,error,status:status(pid)}}))}catch{}}
async function syncNow(pid){if(running.has(pid))return running.get(pid);const task=(async()=>{emitSync(pid,'syncing');try{const local=await collect(pid),remote=await pull(pid),merged=merge(local,remote);await apply(pid,merged);await push(pid,merged);const c=cfg(pid);saveCfg(pid,{...c,last_sync:Date.now(),last_error:'',last_direction:'merge',enabled:true,dirty_at:0});emitSync(pid,'done');return merged}catch(e){const c=cfg(pid);saveCfg(pid,{...c,last_error:e.message||String(e)});emitSync(pid,'error',e.message||String(e));throw e}finally{running.delete(pid)}})();running.set(pid,task);return task}
async function pullOnly(pid){const remote=await pull(pid);if(!remote)throw new Error('Nog geen cloudprofiel gevonden.');const local=await collect(pid),merged=merge(local,remote);await apply(pid,merged);const c=cfg(pid);saveCfg(pid,{...c,last_sync:Date.now(),last_error:'',last_direction:'cloud→lokaal',enabled:true});emitSync(pid,'done');return merged}
async function pushOnly(pid){const local=await collect(pid);await push(pid,local);const c=cfg(pid);saveCfg(pid,{...c,last_sync:Date.now(),last_error:'',last_direction:'lokaal→cloud',enabled:true,dirty_at:0});emitSync(pid,'done');return local}
async function signOut(pid){const c=cfg(pid);try{if(c.access_token)await request(pid,'/auth/v1/logout',{method:'POST',headers:{Authorization:`Bearer ${c.access_token}`}})}catch{}saveCfg(pid,{...c,access_token:'',refresh_token:'',expires_at:0,user:null,enabled:false,last_error:''});if(activePid===pid)stopAuto()}
function markDirty(pid){if(suspendDirty||!pid)return;const c=cfg(pid);saveCfg(pid,{...c,dirty_at:Date.now()});if(!c.enabled||!navigator.onLine)return;clearTimeout(dirtyTimer);dirtyTimer=setTimeout(()=>syncNow(pid).catch(()=>{}),2500)}
function stopAuto(){clearInterval(timer);clearTimeout(dirtyTimer);timer=null;dirtyTimer=null;activePid=''}
function startAuto(pid){stopAuto();activePid=pid;const c=cfg(pid);if(!c.enabled)return;const run=()=>navigator.onLine&&syncNow(pid).catch(()=>{});setTimeout(run,900);timer=setInterval(run,2*60*1000);if(!focusBound){window.addEventListener('focus',()=>{const id=S().currentProfileId();if(id&&cfg(id).enabled)syncNow(id).catch(()=>{})});focusBound=true}if(!visibilityBound){document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){const id=S().currentProfileId();if(id&&cfg(id).enabled)syncNow(id).catch(()=>{})}});visibilityBound=true}if(!onlineBound){window.addEventListener('online',()=>{const id=S().currentProfileId();if(id&&cfg(id).enabled)syncNow(id).catch(()=>{})});onlineBound=true}}
async function testConnection(pid){const token=await access(pid),c=cfg(pid);const d=await request(pid,'/auth/v1/user',{headers:{Authorization:`Bearer ${token}`}});return d||c.user}
async function restoreRemote({url,key,email,password}){const d=await rawRequest(url,key,'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});if(!d.access_token||!d.user?.id)throw new Error('Aanmelden mislukt.');let rows=await rawRequest(url,key,`/rest/v1/athenaeum_state?user_id=eq.${encodeURIComponent(d.user.id)}&profile_key=eq.${CLOUD_KEY}&select=payload,updated_at`,{headers:{Authorization:`Bearer ${d.access_token}`}});if(!(Array.isArray(rows)&&rows[0]))rows=await rawRequest(url,key,`/rest/v1/athenaeum_state?user_id=eq.${encodeURIComponent(d.user.id)}&select=payload,updated_at&order=updated_at.desc&limit=1`,{headers:{Authorization:`Bearer ${d.access_token}`}});const payload=Array.isArray(rows)&&rows[0]?.payload?rows[0].payload:null;if(!payload)throw new Error('Voor dit cloudaccount is nog geen Athenaeum-profiel opgeslagen.');return{auth:d,payload,url,key,email}}
function adoptSession(pid,r){saveCfg(pid,{...cfg(pid),url:r.url,key:r.key,email:r.email,access_token:r.auth.access_token,refresh_token:r.auth.refresh_token,user:r.auth.user,expires_at:Date.now()+((r.auth.expires_in||3600)*1000),enabled:true,cloud_profile_key:CLOUD_KEY,last_error:''})}
window.addEventListener('athenaeum-local-change',e=>{const pid=e.detail?.profile_id;if(pid)markDirty(pid)});
window.addEventListener('athenaeum-profile-change',()=>{const pid=S().currentProfileId();if(pid)markDirty(pid)});
window.AthSync={cfg,saveCfg,status,auth,access,request,rawRequest,syncNow,startAuto,stopAuto,collect,pull,push,pullOnly,pushOnly,testConnection,signOut,markDirty,restoreRemote,adoptSession,apply,merge,cloudKey:()=>CLOUD_KEY};
})();
