(function(){
'use strict';
const S=()=>window.AthStore;
function cfg(pid){return S().getProfileData(pid,'sync',{url:'',key:'',email:'',access_token:'',refresh_token:'',expires_at:0,user:null,enabled:false,last_sync:0,cloud_profile_key:''})}
function saveCfg(pid,c){S().setProfileData(pid,'sync',c)}
async function request(pid,path,opt={}){const c=cfg(pid);if(!c.url||!c.key)throw new Error('Supabase URL/key ontbreken.');const headers={'apikey':c.key,'Content-Type':'application/json',...(opt.headers||{})};const r=await fetch(c.url.replace(/\/$/,'')+path,{...opt,headers});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||`${r.status} ${r.statusText}`);return data}
async function storeSession(pid,d){const c=cfg(pid);saveCfg(pid,{...c,access_token:d.access_token,refresh_token:d.refresh_token,user:d.user,expires_at:Date.now()+((d.expires_in||3600)*1000),enabled:true})}
async function auth(pid,email,password,signup=false){const c=cfg(pid);saveCfg(pid,{...c,email});const d=await request(pid,signup?'/auth/v1/signup':'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});if(d.access_token)await storeSession(pid,d);return d}
async function access(pid){let c=cfg(pid);if(c.access_token&&c.expires_at>Date.now()+60000)return c.access_token;if(!c.refresh_token)throw new Error('Meld eerst aan.');const d=await request(pid,'/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:c.refresh_token})});await storeSession(pid,d);return d.access_token}
function collect(pid){const p=S().loadProfiles().find(x=>x.id===pid);const data={};Object.keys(localStorage).filter(k=>k.startsWith(`ath_${pid}_`)&&!k.endsWith('_sync')).forEach(k=>{try{data[k.slice(`ath_${pid}_`.length)]=JSON.parse(localStorage.getItem(k))}catch{}});return{schema:1,profile:{id:p.id,name:p.name,avatar:p.avatar,icecubes:p.icecubes,updated_at:p.updated_at},data,updated_at:Date.now()}}
function merge(local,remote){if(!remote)return local;const out={schema:1,profile:(remote.profile?.updated_at||0)>(local.profile?.updated_at||0)?remote.profile:local.profile,data:{...local.data},updated_at:Date.now()};for(const[k,v]of Object.entries(remote.data||{})){const lv=out.data[k];if(v&&typeof v==='object'&&!Array.isArray(v)&&lv&&typeof lv==='object'&&!Array.isArray(lv)){out.data[k]={...lv,...v}}else if(lv==null){out.data[k]=v}else{const rt=v?.updated_at||0,lt=lv?.updated_at||0;if(rt>=lt)out.data[k]=v}}return out}
function apply(pid,payload){if(payload.profile){const ps=S().loadProfiles(),i=ps.findIndex(p=>p.id===pid);if(i>=0){ps[i]={...ps[i],name:payload.profile.name||ps[i].name,avatar:payload.profile.avatar||ps[i].avatar,icecubes:payload.profile.icecubes??ps[i].icecubes,updated_at:Math.max(ps[i].updated_at||0,payload.profile.updated_at||0)};S().saveProfiles(ps)}}for(const[k,v]of Object.entries(payload.data||{}))S().setProfileData(pid,k,v)}
async function pull(pid){const token=await access(pid),c=cfg(pid),u=c.user;if(!u?.id)throw new Error('Gebruiker ontbreekt.');let cloudKey=c.cloud_profile_key||'';if(!cloudKey){const rows=await request(pid,`/rest/v1/athenaeum_state?user_id=eq.${encodeURIComponent(u.id)}&select=profile_key,payload,updated_at&order=updated_at.desc&limit=1`,{headers:{Authorization:`Bearer ${token}`}});if(Array.isArray(rows)&&rows[0]){cloudKey=rows[0].profile_key;saveCfg(pid,{...cfg(pid),cloud_profile_key:cloudKey});return rows[0].payload||null}cloudKey=pid;saveCfg(pid,{...cfg(pid),cloud_profile_key:cloudKey});return null}const rows=await request(pid,`/rest/v1/athenaeum_state?user_id=eq.${encodeURIComponent(u.id)}&profile_key=eq.${encodeURIComponent(cloudKey)}&select=payload,updated_at`,{headers:{Authorization:`Bearer ${token}`}});return Array.isArray(rows)&&rows[0]?.payload?rows[0].payload:null}
async function push(pid,payload){const token=await access(pid),c=cfg(pid),u=c.user;if(!u?.id)throw new Error('Gebruikers-ID ontbreekt.');const cloudKey=c.cloud_profile_key||pid;if(!c.cloud_profile_key)saveCfg(pid,{...c,cloud_profile_key:cloudKey});await request(pid,'/rest/v1/athenaeum_state?on_conflict=user_id,profile_key',{method:'POST',headers:{Authorization:`Bearer ${token}`,Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:u.id,profile_key:cloudKey,payload,updated_at:new Date().toISOString()})})}
async function syncNow(pid){const local=collect(pid),remote=await pull(pid),merged=merge(local,remote);apply(pid,merged);await push(pid,merged);const c=cfg(pid);saveCfg(pid,{...c,last_sync:Date.now(),enabled:true});return merged}
let timer=null;let focusBound=false;function startAuto(pid){clearInterval(timer);const c=cfg(pid);if(!c.enabled)return;const run=()=>syncNow(pid).catch(()=>{});setTimeout(run,1500);timer=setInterval(run,5*60*1000);if(!focusBound){window.addEventListener('focus',()=>{const id=S().currentProfileId();if(id&&cfg(id).enabled)syncNow(id).catch(()=>{})});focusBound=true}}
window.AthSync={cfg,saveCfg,auth,syncNow,startAuto,collect,pull,push,access,request};
})();
