
(function(){
'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],S=AthStore;const params=new URLSearchParams(location.search);const PID=params.get('ath_profile')||S.currentProfileId();if(PID)S.setCurrentProfile(PID);const profile=()=>S.loadProfiles().find(x=>x.id===PID);let seed=null,state=null,session=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(){return 'paideia_state'}function defaultState(){return{version:1,streak:0,icecubes:2,last_completed:'',completed_dates:[],daily_count:0,ancient_index:0,general_index:0,gk_index:0,skill_index:0,weekly_scores:[],monthly_scores:[],history:[],mastery:{ancient:0,general_history:0,general_knowledge:0,skill:0},updated_at:Date.now()}}
function loadState(){state=S.getProfileData(PID,key(),defaultState());state={...defaultState(),...state};return state}function save(){state.updated_at=Date.now();S.setProfileData(PID,key(),state)}function iso(d=new Date()){const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,10)}function dayDiff(a,b){return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}function toast(x){S.toast(x)}
async function loadSeed(){seed=window.PAIDEIA_SEED}
function knowledgePacks(){return S.getProfileData(PID,'knowledge_packs',[])}
function groundedPacks(domain){return knowledgePacks().filter(p=>p&&p.domain===domain&&p.source?.source_class!=='model_supplement')}
function groundedQuestions(domain){const out=[];for(const pack of groundedPacks(domain)){const lm=Object.fromEntries((pack.lessons||[]).map(l=>[l.id,l]));for(const q of pack.questions||[]){const lesson=lm[q.lesson_id]||{};const page=(q.source_refs||[])[0]?.physical_page||(lesson.source_refs||[])[0]?.physical_page||'';out.push({...q,domain,topic:lesson.title||pack.title||domain,source_class:pack.source?.source_class||'user_corpus',source_label:[pack.source?.author,pack.source?.title,page?`p. ${page}`:''].filter(Boolean).join(' · ')})}}return out}
function historyReady(domain){return groundedQuestions(domain).length>0}
function historyReadyAll(){return historyReady('ancient')&&historyReady('general_history')}
function checkStreak(){if(!state.last_completed)return;const diff=dayDiff(state.last_completed,iso());if(diff<=1)return;const missed=diff-1;state.pending_missed=missed;if(state.icecubes>=missed){$('#freezeText').textContent=`Je hebt ${missed} dag${missed===1?'':'en'} gemist. Gebruik ${missed} ijsblokje${missed===1?'':'s'} om de streak te behouden?`;$('#useFreeze').textContent=`🧊 Gebruik ${missed}`;$('#freezeModal').classList.add('open')}else{state.streak=0;state.pending_missed=0;save();toast('Streak verbroken: onvoldoende ijsblokjes om alle gemiste dagen te bevriezen.')}}
function nextSunday(){const d=new Date(),delta=(7-d.getDay())%7;d.setDate(d.getDate()+delta);return d.toLocaleDateString('nl-BE',{weekday:'long',day:'numeric',month:'long'})}
function extraDue(){return state.daily_count>0 && state.daily_count%3===0}
function renderHome(){const a=seed.ancient_topics[state.ancient_index%seed.ancient_topics.length],g=seed.general_history_topics[state.general_index%seed.general_history_topics.length],x=extraDue();$('#p-home').innerHTML=`<div class="pa-hero slide-up"><div class="spread"><div><div class="chip">PAIDEIA · DAG ${state.daily_count+1}</div><h2>Goedemorgen, ${esc(profile()?.name||'')}</h2><p>Dagelijks 30 minuten geschiedenis. Iedere derde leeravond/dag komt er een extra blok algemene kennis of een praktische skill bij.</p></div><img src="${window.ATH_ASSET_DATA?.avatars?.[profile()?.avatar||'bust']||('../../assets/avatars/'+(profile()?.avatar||'bust')+'.svg')}" style="width:78px;height:78px;border-radius:50%"></div></div><div class="stat-grid"><div class="stat"><div class="k">🔥 Streak</div><div class="v">${state.streak}</div></div><div class="stat"><div class="k">🧊 IJsblokjes</div><div class="v">${state.icecubes}</div></div><div class="stat"><div class="k">Volgend examen</div><div class="v" style="font-size:18px">${nextSunday()}</div></div><div class="stat"><div class="k">Vandaag</div><div class="v">30${x?'+18':''} min</div></div></div><div class="grid two" style="margin-top:18px"><div class="card"><h3>Vandaag</h3><div class="daily-block"><div class="spread"><div><h4>🏺 Oude geschiedenis</h4><div class="tiny">20 min · 66% van geschiedenisblok</div></div><button class="btn primary" data-session="ancient">Start</button></div><p><strong>${esc(a.title)}</strong></p><div class="knowledge-tags">${a.structure_tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div><div class="daily-block" style="margin-top:10px"><div class="spread"><div><h4>🌍 Algemene geschiedenis</h4><div class="tiny">10 min · 33% van geschiedenisblok</div></div><button class="btn primary" data-session="general_history">Start</button></div><p><strong>${esc(g.title)}</strong></p></div>${x?`<div class="daily-block" style="margin-top:10px;border-color:#cbb6d2"><div class="spread"><div><h4>${state.daily_count%6===0?'🛠️ Skill sprint':'🧠 Algemene kennis'}</h4><div class="tiny">extra sessie · vervangt geschiedenis niet</div></div><button class="btn gold" data-session="${state.daily_count%6===0?'skill':'general_knowledge'}">Start extra</button></div></div>`:''}<div class="row" style="margin-top:12px"><button class="btn gold" id="fullDaily">Volledige dagsessie starten</button></div></div><div class="card"><h3>Waarom deze verdeling?</h3><p>Je specialisatie krijgt dagelijks de meeste tijd. Algemene geschiedenis bouwt een breed chronologisch raamwerk. Algemene kennis blijft aanvullend zodat het systeem geen blok aan je been wordt.</p><p class="tiny">Praktische skills worden niet volledig willekeurig gestrooid: ze komen ongeveer om de 6 dagen terug. Daardoor blijft een kennissprint coherent, maar bouw je toch brede praktische basiskennis op.</p></div></div>`;$$('[data-session]').forEach(b=>b.onclick=()=>startSession(b.dataset.session));$('#fullDaily').onclick=()=>startSession('daily')}
function questionsFor(domain,count){if(domain==='ancient'||domain==='general_history'){const grounded=groundedQuestions(domain);return shuffle(grounded).slice(0,Math.min(count,grounded.length))}const all=seed.questions.filter(q=>q.domain===domain).map(q=>({...q,source_class:'model_supplement',source_label:'Paideia modelaanvulling'}));const topic=domain==='general_knowledge'?seed.general_knowledge_topics[state.gk_index%seed.general_knowledge_topics.length].title:seed.skill_topics[state.skill_index%seed.skill_topics.length].title;let pool=all.filter(q=>q.topic===topic);if(pool.length<count)pool=all;return shuffle(pool).slice(0,count)}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startSession(kind){let qs=[],title='';if((kind==='ancient'&&!historyReady('ancient'))||(kind==='general_history'&&!historyReady('general_history'))||(kind==='daily'&&!historyReadyAll())){toast('Geschiedenistraining is nog niet geactiveerd. Importeer eerst gecontroleerde kennis-packs uit je eigen boeken/scans.');showPage('library');return}if(kind==='daily'){qs=[...questionsFor('ancient',6),...questionsFor('general_history',3)];if(extraDue())qs.push(...questionsFor(state.daily_count%6===0?'skill':'general_knowledge',3));title='Volledige dagsessie'}else{const n=kind==='ancient'?6:kind==='general_history'?3:3;qs=questionsFor(kind,n);title=kind==='ancient'?'Oude geschiedenis':kind==='general_history'?'Algemene geschiedenis':kind==='skill'?'Skill sprint':'Algemene kennis'}session={kind,title,questions:qs,index:0,answers:[],started_at:Date.now()};$('#sessionTitle').textContent=title;$('#sessionMeta').textContent=`${qs.length} vragen · actief ophalen + zelfcontrole`;$('#sessionModal').classList.add('open');renderQuestion()}
function aiRubricFor(q){
  const parts=[];
  if(q.answer)parts.push('Richtantwoord: '+q.answer);
  if(q.keywords?.length)parts.push('Ankerpunten: '+q.keywords.join(', '));
  if(q.correct!=null)parts.push('Correcte optie-index: '+q.correct);
  return parts.join('\n')||'Geen volledig modelantwoord beschikbaar; beoordeel conservatief op taakuitvoering en expliciete broncontext.';
}
function aiContextFor(q){
  return JSON.stringify({topic:q.topic||'',source_label:q.source_label||'',source_class:q.source_class||'',source_refs:q.source_refs||[],provenance:q.provenance||''},null,2)
}
function renderAiFeedback(f,meta={}){
  const box=$('#aiTeacherFeedback');if(!box)return;
  if(!f){box.classList.add('hidden');box.innerHTML='';return}
  box.classList.remove('hidden');
  box.innerHTML=`<div class="ai-teacher-card"><div class="spread"><div><strong>🧑‍🏫 AI-docent</strong><div class="tiny">feedback op jouw antwoord · geen modelantwoord</div></div><span class="chip">${esc(f.score_percent)}%</span></div>
    <p><strong>${esc(f.verdict)}</strong> — ${esc(f.feedback)}</p>
    ${(f.strengths||[]).length?`<h4>Sterk</h4><ul>${f.strengths.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}
    ${(f.missing_points||[]).length?`<h4>Nog aanvullen</h4><ul>${f.missing_points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}
    <div class="review-box"><strong>Volgende stap</strong><p>${esc(f.next_action)}</p>${f.hint?`<div class="tiny"><strong>Hint:</strong> ${esc(f.hint)}</div>`:''}</div>
    <div class="tiny" style="margin-top:8px">Bronbinding: ${esc(f.source_grounding||'niet vermeld')}${meta.quota?` · ${esc(AthAI.quotaText(meta.quota))}`:''}</div></div>`
}
async function askAiTeacher(){
  const q=session?.questions?.[session.index];if(!q)return;
  const answer=$('#openAnswer')?.value.trim()||'';
  if(answer.length<20)return toast('Schrijf eerst een inhoudelijk antwoord voor de AI-docent.');
  if(!window.AthAI)return toast('AI-docent is nog niet geladen.');
  const btn=$('#aiTeacherBtn');if(btn){btn.disabled=true;btn.textContent='AI-docent beoordeelt…'}
  try{
    const r=await AthAI.feedback(PID,{mode:'paideia_feedback',question:q.prompt,answer,rubric:aiRubricFor(q),context:aiContextFor(q),domain:q.domain||session.kind});
    session.aiCurrent={...r.feedback,answer,model_used:r.model_used,quota:r.quota,at:Date.now()};
    const score=$('#selfScore');if(score)score.value=r.feedback.score_percent;
    renderAiFeedback(r.feedback,{quota:r.quota});
  }catch(e){toast(e.message)}finally{if(btn){btn.disabled=false;btn.textContent='AI-docent: geef feedback'}}
}
function renderQuestion(){const q=session.questions[session.index];session.aiCurrent=null;$('#sessionBar').style.width=`${session.index/session.questions.length*100}%`;let html=`<div class="question-card"><div class="chip">${esc(q.type)} · ${esc(q.topic)}</div>${q.source_label?`<div class="tiny" style="margin-top:7px">📚 ${esc(q.source_label)}${q.source_class==='model_supplement'?' · aanvulling':''}</div>`:''}<h3 style="margin-top:12px">${esc(q.prompt)}</h3>`;if(q.options?.length)html+=q.options.map((o,i)=>`<button class="option" data-opt="${i}">${esc(o)}</button>`).join('');else html+=`<textarea id="openAnswer" style="width:100%;min-height:140px;border:1px solid #d8d0c2;border-radius:14px;padding:12px" placeholder="Antwoord uit het hoofd. Schrijf compact maar volledig."></textarea><div class="row" style="margin-top:10px"><button class="btn ai-teacher-btn" id="aiTeacherBtn">🧑‍🏫 AI-docent: geef feedback</button></div><div id="aiTeacherFeedback" class="hidden" style="margin-top:10px"></div>`;html+=`<div id="guideline" class="review-box hidden" style="margin-top:12px"><strong>Richtlijn / zelfcorrectie</strong><p>${q.answer?esc(q.answer):q.keywords?.length?'Controleer of je minstens deze ankerpunten behandelt: '+q.keywords.map(esc).join(', '):'Vergelijk met je bronnotities en beoordeel of je vraag, structuur en causaliteit volledig hebt behandeld.'}</p><label>${q.options?.length?'Zelfscore':'Score / zelfcorrectie'} (0-100%) <input id="selfScore" type="number" min="0" max="100" value="75" style="width:90px"></label></div></div>`;$('#questionHost').innerHTML=html;$$('[data-opt]').forEach(b=>b.onclick=()=>{$$('[data-opt]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');session.selected=+b.dataset.opt});if($('#aiTeacherBtn'))$('#aiTeacherBtn').onclick=askAiTeacher;$('#revealBtn').textContent='Toon richtlijn';$('#nextBtn').textContent=session.index===session.questions.length-1?'Afronden':'Volgende'}
function reveal(){const g=$('#guideline');g.classList.remove('hidden');$('#revealBtn').textContent='Richtlijn zichtbaar'}function nextQ(){const q=session.questions[session.index];const score=+($('#selfScore')?.value||75);session.answers.push({q:q.id,score});if(session.index<session.questions.length-1){session.index++;session.selected=null;renderQuestion();return}finishSession()}
function finishSession(){const avg=Math.round(session.answers.reduce((a,b)=>a+b.score,0)/Math.max(1,session.answers.length));const kind=session.kind;state.history.push({id:S.uid(),date:iso(),kind,title:session.title,score:avg,ai_reviewed:session.answers.filter(x=>x.ai_feedback).length,updated_at:Date.now()});if(['daily','ancient'].includes(kind))state.mastery.ancient=Math.round((state.mastery.ancient*3+avg)/4);if(['daily','general_history'].includes(kind))state.mastery.general_history=Math.round((state.mastery.general_history*3+avg)/4);if(kind==='general_knowledge')state.mastery.general_knowledge=Math.round((state.mastery.general_knowledge*3+avg)/4);if(kind==='skill')state.mastery.skill=Math.round((state.mastery.skill*3+avg)/4);if(kind==='daily'){completeDaily();advanceTopics()}else if(kind==='ancient'){state.ancient_index=(state.ancient_index+1)%seed.ancient_topics.length}else if(kind==='general_history'){state.general_index=(state.general_index+1)%seed.general_history_topics.length}else if(kind==='general_knowledge'){state.gk_index=(state.gk_index+1)%seed.general_knowledge_topics.length}else if(kind==='skill'){state.skill_index=(state.skill_index+1)%seed.skill_topics.length}save();$('#sessionModal').classList.remove('open');toast(`Sessie afgerond: ${avg}%`);renderHome()}
function completeDaily(){const today=iso();if(state.last_completed===today)return;const diff=state.last_completed?dayDiff(state.last_completed,today):1;if(diff===1||!state.last_completed)state.streak+=1;state.last_completed=today;if(!state.completed_dates.includes(today))state.completed_dates.push(today);state.daily_count+=1}function advanceTopics(){state.ancient_index=(state.ancient_index+1)%seed.ancient_topics.length;if(state.daily_count%2===0)state.general_index=(state.general_index+1)%seed.general_history_topics.length;if(extraDue())state.gk_index=(state.gk_index+1)%seed.general_knowledge_topics.length}
function renderLearn(){$('#p-learn').innerHTML=`<div class="hero"><h2>Leren</h2><p>De kern wordt later opgebouwd uit je eigen gecontroleerde scans en boeken. Het meegeleverde modelpakket is alleen een offline demonstratielaag.</p></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>🏺 Oude geschiedenis</h3><p>Niet alleen gebeurtenissen: ook personen, plaatsen, instituties, begrippen, bronnen, historiografische problemen, structuren, evoluties, revoluties, conjuncturen, processen en netwerken.</p><button class="btn primary" data-session="ancient">Start 20 min</button></div><div class="card"><h3>🌍 Algemene geschiedenis</h3><p>Dagelijkse breedte: chronologie, vergelijkingen, staatsvorming, economie, sociale structuren en grotere transities.</p><button class="btn primary" data-session="general_history">Start 10 min</button></div></div>`;$$('[data-session]').forEach(b=>b.onclick=()=>startSession(b.dataset.session))}
function examQs(monthly=false){if(!historyReadyAll())return [];const base=[...questionsFor('ancient',6),...questionsFor('general_history',4)];return base.map((q,i)=>({...q,type:'open',prompt:monthly?`Mastery-vraag ${i+1}: ${q.prompt}`:`Examenvraag ${i+1}: ${q.prompt}`}))}function startExam(monthly=false){if(!historyReadyAll()){toast('Examens worden vrijgegeven zodra Oude én Algemene Geschiedenis brongebonden kennis-packs bevatten.');showPage('library');return}session={kind:monthly?'monthly_exam':'weekly_exam',title:monthly?'Maandelijkse mastery check':'Wekelijks examen',questions:examQs(monthly),index:0,answers:[],started_at:Date.now()};$('#sessionTitle').textContent=session.title;$('#sessionMeta').textContent='Universitaire stijl · cumulatief · open antwoorden';$('#sessionModal').classList.add('open');renderQuestion()}
const oldFinish=finishSession;
function finishExamIfNeeded(){if(!session.kind.endsWith('_exam'))return false;const avg=Math.round(session.answers.reduce((a,b)=>a+b.score,0)/Math.max(1,session.answers.length));const rec={date:iso(),score:avg,id:S.uid(),ai_reviewed:session.answers.filter(x=>x.ai_feedback).length};if(session.kind==='weekly_exam')state.weekly_scores.push(rec);else state.monthly_scores.push(rec);if(avg>=75)state.icecubes+=1;state.history.push({...rec,kind:session.kind,title:session.title});save();$('#sessionModal').classList.remove('open');toast(`Examen: ${avg}%${avg>=75?' · 🧊 +1':''}`);renderExam();return true}
function nextQ2(){const q=session.questions[session.index],answer=$('#openAnswer')?.value.trim()||'',score=session.aiCurrent?.score_percent??+($('#selfScore')?.value||75);session.answers.push({q:q.id,score,answer,ai_feedback:session.aiCurrent||null});if(session.index<session.questions.length-1){session.index++;renderQuestion();return}if(!finishExamIfNeeded())finishSession()}
function renderExam(){const w=state.weekly_scores.at(-1),m=state.monthly_scores.at(-1);$('#p-exam').innerHTML=`<div class="hero"><h2>Examens</h2><p>Geen losse quizjes alleen: wekelijkse en maandelijkse toetsen vragen synthese, volledige evoluties, periodisering en verbanden zoals aan de universiteit.</p></div><div class="grid two" style="margin-top:16px"><div class="card exam-card"><h3>Wekelijks examen</h3><p>±45 min. Cumulatief, met open vragen, verklaringen en vergelijkingen.</p><button class="btn primary" id="weeklyBtn">Start weekexamen</button><p class="tiny">Laatste: ${w?w.score+'%':'nog geen'}</p></div><div class="card exam-card"><h3>Maandelijkse mastery check</h3><p>Brede synthese over structuren, evoluties en chronologische samenhang.</p><button class="btn gold" id="monthlyBtn">Start mastery check</button><p class="tiny">Laatste: ${m?m.score+'%':'nog geen'}</p></div></div>`;$('#weeklyBtn').onclick=()=>startExam(false);$('#monthlyBtn').onclick=()=>startExam(true)}
function renderKnowledge(){const packs=S.getProfileData(PID,'knowledge_packs',[]);$('#p-knowledge').innerHTML=`<div class="hero"><h2>Kennisbank</h2><p>Terugvinden wat je ooit geleerd hebt. Zodra je eigen boeken zijn omgezet in kennis-packs verschijnt hier brongebonden kennis met exacte paginaverwijzingen.</p></div><div class="stat-grid"><div class="stat"><div class="k">Oude geschiedenis mastery</div><div class="v">${state.mastery.ancient}%</div></div><div class="stat"><div class="k">Algemene geschiedenis</div><div class="v">${state.mastery.general_history}%</div></div><div class="stat"><div class="k">Algemene kennis</div><div class="v">${state.mastery.general_knowledge}%</div></div><div class="stat"><div class="k">Skills</div><div class="v">${state.mastery.skill}%</div></div></div><div class="card" style="margin-top:16px"><h3>Kennis-packs</h3>${packs.length?packs.map(p=>`<div style="padding:10px 0;border-bottom:1px solid #e1d9ca"><strong>${esc(p.title)}</strong><div class="tiny">${esc(p.source?.title||'')} · ${p.lessons?.length||0} lessen</div></div>`).join(''):'<p class="muted">Nog geen brongebonden kennis-packs geïmporteerd. Geschiedenistraining en examens blijven daarom vergrendeld; modelvragen zijn alleen aanvulling voor algemene kennis/skills.</p>'}</div>`}
function renderLibrary(){const packs=S.getProfileData(PID,'knowledge_packs',[]);$('#p-library').innerHTML=`<div class="hero"><h2>Bronnen</h2><p>Paideia geeft voorrang aan jouw gecontroleerde werken. Nieuwe contentpacks mogen pas als hoofdanker gelden wanneer titel, auteur en paginaverwijzingen controleerbaar zijn.</p></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Prioriteit</h3><p>1. Jouw scans/boeken<br>2. universitaire compendia<br>3. wetenschappelijke monografieën/artikels<br>4. modelkennis als aanvulling</p></div><div class="card"><h3>Geïmporteerd</h3><p>${packs.length} kennis-pack(s)</p><a class="btn" href="../../index.html">Importeer via Athenaeum Bibliotheek</a></div></div>`}
async function renderTelegram(){const n=window.AthTelegram?.notify(PID)||{morning:'08:00',reminder:'18:00',timezone:'Europe/Brussels'};$('#p-telegram').innerHTML=`<div class="hero"><h2>Telegram</h2><p>Laat Athenaeum Bot je 's ochtends vertellen wat vandaag gepland staat, hoeveel dagen je streak telt en wanneer je volgende examen komt. Een tweede melding kan je later herinneren als de dagsessie nog openstaat.</p></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>🔔 Meldingsschema</h3><div class="field"><label>Ochtend</label><input id="tgMorning" type="time" value="${esc(n.morning||'08:00')}"></div><div class="field" style="margin-top:10px"><label>Reminder</label><input id="tgReminder" type="time" value="${esc(n.reminder||'18:00')}"></div><div class="field" style="margin-top:10px"><label>Tijdzone</label><input id="tgTimezone" value="${esc(n.timezone||'Europe/Brussels')}"></div><button class="btn" id="tgSave" style="margin-top:12px">Bewaar schema</button></div><div class="card"><div class="spread"><h3>🤖 Athenaeum Bot</h3><span class="chip" id="tgState">controleren…</span></div><p class="muted" id="tgInfo">Telegram gebruikt dezelfde veilige Supabase-login als synchronisatie. Je bot-token staat nooit in de website.</p><div class="row"><button class="btn primary" id="tgPair">Koppelen</button><button class="btn" id="tgTest">Testmelding</button><button class="btn" id="tgDisconnect">Ontkoppelen</button><button class="btn" id="tgDiagnose">Diagnose</button><a class="btn" href="../../docs/TELEGRAM_SETUP_V1_0_5.txt" target="_blank">Stappenplan</a></div></div></div>`;const refresh=async()=>{const chip=$('#tgState'),info=$('#tgInfo');if(!window.AthTelegram){chip.textContent='niet beschikbaar';return}const s=await AthTelegram.status(PID);chip.textContent=s.connected?'✅ gekoppeld':'niet gekoppeld';info.textContent=s.connected?`Athenaeum Bot is gekoppeld${s.bot_username?' met @'+s.bot_username:''}.`:(s.error||'Koppel eerst de bot.')};$('#tgSave').onclick=async()=>{const x={morning:$('#tgMorning').value,reminder:$('#tgReminder').value,timezone:$('#tgTimezone').value};AthTelegram.saveNotify(PID,x);try{await AthTelegram.updateSchedule(PID,x)}catch{}toast('Meldingsschema bewaard.')};$('#tgPair').onclick=async()=>{try{const r=await AthTelegram.pair(PID);$('#tgInfo').innerHTML=`Koppelcode <strong>${r.code}</strong> is 30 minuten geldig. ${r.link?`<a href="${r.link}" target="_blank">Open @${esc(r.bot_username)} in Telegram</a>`:'Stuur in Athenaeum Bot: /start '+r.code}`;toast('Koppelcode gemaakt.')}catch(e){toast(e.message)}};$('#tgTest').onclick=async()=>{try{await AthTelegram.test(PID);toast('Testmelding verstuurd.')}catch(e){toast(e.message)}};$('#tgDisconnect').onclick=async()=>{try{await AthTelegram.disconnect(PID);toast('Telegram ontkoppeld.');refresh()}catch(e){toast(e.message)}};$('#tgDiagnose').onclick=async()=>{const r=await AthTelegram.diagnose(PID);$('#tgInfo').innerHTML=(r.steps||[]).map(x=>'• '+esc(x)).join('<br>')};refresh()}
function showPage(n){['home','learn','exam','knowledge','library','telegram'].forEach(x=>$('#p-'+x).classList.toggle('hidden',x!==n));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===n));const t={home:['Paideia','Snel, efficiënt en cumulatief leren'],learn:['Leren','Dagelijkse kennisblokken'],exam:['Examens','Wekelijks en maandelijks'],knowledge:['Kennisbank','Wat je duurzaam beheerst'],library:['Bronnen','Herkomst en kennis-packs'],telegram:['Telegram','Ochtendmeldingen, reminders en examenaftelling']}[n];$('#paTitle').textContent=t[0];$('#paSub').textContent=t[1];({home:renderHome,learn:renderLearn,exam:renderExam,knowledge:renderKnowledge,library:renderLibrary,telegram:renderTelegram}[n])();scrollTo({top:0,behavior:'smooth'})}
function back(){location.href='../../index.html?resume=1&profile='+encodeURIComponent(PID)+'&page=apps'}function updateMode(){$('#paMode').textContent=(matchMedia('(display-mode: standalone)').matches?'App':'Web')+' · '+(innerWidth<=900?'telefoon':'laptop')}
async function init(){if(!PID||!profile())return location.href='../../index.html';await loadSeed();loadState();checkStreak();window.AthSync?.startAuto(PID);showPage('home');$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#backAth').onclick=back;$('#backAthTop').onclick=back;$('#mBack').onclick=back;$('#closeSession').onclick=()=>$('#sessionModal').classList.remove('open');$('#revealBtn').onclick=reveal;$('#nextBtn').onclick=nextQ2;$('#useFreeze').onclick=()=>{const n=state.pending_missed||1;if(state.icecubes>=n){state.icecubes-=n;state.last_completed=iso(new Date(Date.now()-86400000));state.pending_missed=0;save();$('#freezeModal').classList.remove('open');toast(`Streak bevroren met ${n} ijsblokje${n===1?'':'s'}.`);renderHome()}};$('#breakStreak').onclick=()=>{state.streak=0;state.last_completed='';save();$('#freezeModal').classList.remove('open');renderHome()};updateMode();addEventListener('resize',updateMode)}
init();
})();

